# Site settings

title: M. Nooranidoost
email: mnooranidoost@fsu.edu

description: > # this means to ignore newlines until "baseurl:"
Florida State University
Department of Mathematics

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
<!-- scholar_username: citations?user=PWU2CdgAAAAJ&hl=en --> 
<!-- github_username:  mnooranidoost --> 

github_username: https://github.com/mnooranidoost
gitlab_username: # your GitLab user name
twitter_username: https://scholar.google.com/citations?user=PWU2CdgAAAAJ&hl=en
linkedin_username: # your LinkedIn user name
scholar_userid: PWU2CdgAAAAJ&hl=en
orcid_id: # your ORCID ID
medium_username: # your Medium username
quora_username: # your Quora username
publons_id: # your ID on Publons
research_gate_profile: # your profile on ResearchGate
blogger_url: # your blogger URL
work_url: # work page URL
keybase_username: # your keybase user name
wikidata_id: # your wikidata id
dblp_url: # your DBLP profile url
stackoverflow_id: #your stackoverflow id




# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Postdoctoral Scholar"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
