# Site settings
title: Steven V. Miller
email: svmille@clemson.edu
description: > # this means to ignore newlines until "baseurl:"
MN

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nooranidoost.com" # the base hostname & protocol for your site
twitter_username: nooranidoost
github_username:  nooranidoost
orcid_id: 0000-0002-6326-9213
google_scholar_id: PWU2CdgAAAAJ&hl=en

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title/
jobtitle: "Postdoctoral Researcher"
excerpt_separator: "<!--more-->"

# SEO stuff
google_author: ""
google_site_verification: ""
bing_webmastertools_id: ""

plugins_dir:
  - jekyll-sitemap

exclude: ['*.Rmd']
